### PR TITLE
Add option to forward options to posthtml-expressions plugin

### PR DESCRIPTION
**Pull request by citrus**
I came across a situation where I needed to use custom delimiters in my html, so I added an option to forward options to [posthtml-expressions](https://github.com/posthtml/posthtml-expressions). 

Available options here: https://github.com/posthtml/posthtml-expressions#options

```js
// module: <div><i>%[ foo ]%</i><b>{{ ignored }}</b></div>
const template = `<module href="./test/module.html" locals='{"foo":"bar"}'></module>`;
const html = await posthtml().use(plugin({ 
  expressions: { 
    delimiters: ['%[', ']%'] 
  } 
})).process(actual).then(result => clean(result.html));

console.log(html)
// <div><i>bar</i><b>{{ ignored }}</b></div>
```

### CODE REVIEW

**Comment by citrus** [comment]
@Scrum Good call out. I've added this option to the readme.

**Comment by cossssmin** [comment]
Thanks for this @citrus (and sorry for the delay!).

@Scrum tests pass, can you please merge and publish a new release? Thanks!

**Comment by cossssmin** [comment]
Actually @citrus can you please rename `posthtmlExpressionsOptions` to just `expressions`? 

This way it's consistent with other PostHTML plugins, like [`posthtml-extend`](https://github.com/posthtml/posthtml-extend#expressions). Thanks!

**Comment by citrus** [comment]
> Actually @citrus can you please rename the `posthtmlExpressionsOptions` option to just `expressions`?
> 
> This way it's consistent with other PostHTML plugins, like [`posthtml-extend`](https://github.com/posthtml/posthtml-extend#expressions). Thanks!

done & done!

**Comment by citrus** [comment]
> Thanks, looks good to me! Let's wait for @Scrum to review and merge/release a new version 👍

Sounds good! Let me know if anything needs to be adjusted.

**Comment by cossssmin** [comment]
Going to merge this now, as we have more issues to attend to (#86) and we'll release a new version with those fixes included, sorry!

**Comment by Scrum** [comment]
@citrus @cossssmin Thanks guys, now available in version 0.9.0

**Pull request merged**
