### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by cossssmin**

### CODE REVIEW

**Comment by anikethsaha** [comment]
can you update the travis config and drop node < 8. async needs node 8+.

**Comment by cossssmin** [comment]
Will do, just finishing updating tests in another branch and will push to this one soon. Thanks!

**Comment by anikethsaha** [comment]
ok just do let me know once its ready for review .

**Comment by cossssmin** [comment]
Made tests pass again in https://github.com/cossssmin/posthtml-modules/tree/refactor

Would it be better to just drop Node < 8 there, close this PR and open one from that `refactor` branch instead?

**Comment by anikethsaha** [comment]
> Made tests pass again in https://github.com/cossssmin/posthtml-modules/tree/refactor
> 
> Would it be better to just drop Node < 8 there, close this PR and open one from that `refactor` branch instead?

cool 👍

**Comment by cossssmin** [comment]
Alright, just to confirm:

```json
{
  "engines": {
    "node": ">=8.0.0"
  }
}
```

**Comment by anikethsaha** [comment]
posthtml supports  6+
cc @Scrum which node version do you think should be supported?

IMO, it should be `>=10.13.0`

**Comment by Scrum** [comment]
@anikethsaha Below 10 I do not see the point, for all packages

**Comment by Scrum** [comment]
@cossssmin please drop support old node

**Comment by anikethsaha** [comment]
@Scrum i pr will be closed , @cossssmin is working on a separate pr https://github.com/posthtml/posthtml-modules/pull/36

**Comment by cossssmin** [comment]
> @Scrum i think pr will be closed , @cossssmin is working on a separate pr #36

Yes, let's continue the conversation in #36

**Pull request closed without merging**
